#!/bin/csh 
#PBS -l nodes=4:ppn=8
#PBS -q workq
#PBS -r n
#PBS -l walltime=48:00:00
#PBS -N fargoADSG
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES
cd $PBS_O_WORKDIR
mpirun ./fargoSG_nonISO -m -b input.par
